version: '3.6'

services: 
  app: 
    build: 
      context: .
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    tty: true
    entrypoint: ["npm", "start"]
    depends_on:
      - database
    networks:
      - nodenetwork

  database: 
    container_name: database
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - node-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - nodenetwork
volumes:
  node-data:

networks:
  nodenetwork:
    driver: bridge